name: Construction d'un projet

on:
  push:
    branches: [ "main" ]
  pull_request:   # en plus : dÃ©clenche aussi lors d'une Pull Request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¥ TÃ©lÃ©charger les sources
      uses: actions/checkout@v4

    - name: â˜• Installer JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: ğŸ—ï¸ Compiler le projet
      run: mvn -B compile

    - name: âœ… Lancer les tests
      run: mvn -B test

    - name: ğŸ“¦ Packager l'application
      run: mvn -B package
